1.
(a)
After we use majority voting combination rule instead of the original combination rule, there is only one line[38] in file outv would be changed which also means that at this line, the vvote is different to vcomb, vvote is 3 but vcomb is 2. But Yv is 3, so vvote generates better result than vcomb.

In [13]:
import pandas as pd
import numpy as np

# tmp = pd.read_csv('outv.csv', header=None).to_numpy()  # pandas does not work!
tmp = np.genfromtxt('outv.csv',delimiter=',')
K = tmp.shape[0]
print(tmp)

Yv = tmp[:,0:3]

print(Yv)

[[2. 2. 2. 2. 2.]
 [3. 3. 2. 2. 3.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 3.]
 [3. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [2. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1.]
 [2. 3. 3. 3. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3.]
 [3. 3. 2. 2. 3.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]
[[2. 2. 2.]
 [3. 3. 2.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [3. 3. 3.]
 [1. 1. 1.]
 [2. 2. 2.]
 [1. 1. 1.]
 [2. 3. 3.]
 [1. 1. 1.]
 [1. 1. 1.]
 [3. 3. 3.]
 [3. 3. 3.]
 [2. 2. 2.]
 [3. 3. 3

In [2]:
from sklearn.metrics import confusion_matrix

Cmatcomb = confusion_matrix(Yv, vvote)

print("Cmatvote: ")
print(Cmatcomb)

Cmatvote: 
[[14  0  0]
 [ 0 16  1]
 [ 0  3 11]]


ynb         yknn        ytree       Yr
3.00E+00	3.00E+00	3.00E+00	3.00E+00
2.00E+00	2.00E+00	2.00E+00	2.00E+00
1.00E+00	1.00E+00	1.00E+00	1.00E+00
3.00E+00	3.00E+00	2.00E+00	2.00E+00
2.00E+00	3.00E+00	3.00E+00	2.00E+00
3.00E+00	2.00E+00	2.00E+00	2.00E+00
2.00E+00	2.00E+00	3.00E+00	2.00E+00
2.00E+00	3.00E+00	3.00E+00	3.00E+00

Above is the combination rule table.

In [3]:
# tmp = pd.read_csv('outv.csv', header=None).to_numpy()  # pandas does not work!
tmp = np.genfromtxt('outv.csv',delimiter=',')
K = tmp.shape[0]
print(K)
vvote = tmp[:,3]
Yv = tmp[:,4]

Cmatcomb = confusion_matrix(Yv, vvote)

print("Cmatmanual. : ")
print(Cmatcomb)

Cmatmanual. : 
[[14  0  0]
 [ 0 16  1]
 [ 0  3 11]]


Write CSV files